Added GridFS support
rozza/mongo-java-driver-reactivestreams pull request #7
Opened 2016-11-30 14:58 UTC by rozza

JAVARS-23

2016-11-30 14:59 UTC, rozza commented on driver/src/main/com/mongodb/reactivestreams/client/gridfs/GridFSBuckets.java
> +        return new GridFSBucketImpl(com.mongodb.async.client.gridfs.GridFSBuckets.create(database.getAsyncMongoDatabase()));
I can't think of a clean way to access the wrapped MongoDatabase without explicitly adding a method to the interface surfacing it.

2016-12-01 12:56 UTC, jyemin commented on driver/src/main/com/mongodb/reactivestreams/client/MongoClients.java
> +import org.bson.codecs.configuration.CodecRegistry;
Why the new import?

2016-12-01 12:56 UTC, jyemin commented on driver/src/main/com/mongodb/reactivestreams/client/gridfs/GridFSBuckets.java
> +        return new GridFSBucketImpl(com.mongodb.async.client.gridfs.GridFSBuckets.create(database.getAsyncMongoDatabase()));
It might be even worse, but we could add an asGridFSBucket method to MongoDatabase.

2016-12-02 16:27 UTC, rozza commented
OK moved all implementation code into the `internal` package.   

The following internal classes are now public:

* `MongoClientImpl` - so can be constructed from `MongoClients`
* `MongoDatabaseImpl` - so can be accessed via `GridFSBuckets`
* `GridFSBucketImpl` - so can be constructed from `GridFSBuckets`
* `GridFSAsyncStreamHelper` - so can be accessed via `AsyncStreamHelper`

2016-12-05 14:14 UTC, jyemin requested changes

2016-12-05 14:14 UTC, jyemin commented on driver/src/main/com/mongodb/reactivestreams/client/MongoDatabase.java
> +
Revert extraneous diff

2016-12-05 14:14 UTC, jyemin commented on driver/src/main/com/mongodb/reactivestreams/client/gridfs/GridFSBuckets.java
> +     * @param database the database instance to use with GridFS
Document the limitation on MongoDatabase implementations that it will accept

2016-12-05 14:14 UTC, jyemin commented on driver/src/test/unit/com/mongodb/reactivestreams/client/gridfs/GridFSBucketSpecification.groovy
> +import com.mongodb.async.client.gridfs.GridFSBucket as WrappedGridFSBucket
Funny red characters...

2016-12-05 14:14 UTC, jyemin commented on driver/src/test/unit/com/mongodb/reactivestreams/client/gridfs/GridFSBucketsSpecification.groovy
> +import com.mongodb.async.client.MongoDatabase as WrappedMongoDatabase
More funny red characters..

2016-12-05 14:14 UTC, jyemin commented on driver/src/main/com/mongodb/reactivestreams/client/internal/GridFSAsyncStreamHelper.java
> +                        error = t;
onError is a terminal state, so shouldn't it invoke the callback as onComplete does?

2016-12-05 14:14 UTC, jyemin commented on driver/src/main/com/mongodb/reactivestreams/client/internal/GridFSAsyncStreamHelper.java
> +                        callback.onResult(null, error);
Any way to test this?  I don't see it invoked when running the tests in the debugger.

2016-12-06 13:20 UTC, rozza commented on driver/src/test/unit/com/mongodb/reactivestreams/client/gridfs/GridFSBucketSpecification.groovy
> +import com.mongodb.async.client.gridfs.GridFSBucket as WrappedGridFSBucket
Yeah its the highlighter being odd.

2016-12-06 14:20 UTC, rozza commented on driver/src/main/com/mongodb/reactivestreams/client/internal/GridFSAsyncStreamHelper.java
> +                        callback.onResult(null, error);
Added a test

2016-12-06 14:20 UTC, rozza commented on driver/src/main/com/mongodb/reactivestreams/client/internal/GridFSAsyncStreamHelper.java
> +                        error = t;
Done

2016-12-06 14:20 UTC, rozza commented on driver/src/test/unit/com/mongodb/reactivestreams/client/gridfs/GridFSBucketsSpecification.groovy
> +import com.mongodb.async.client.MongoDatabase as WrappedMongoDatabase
As above

2016-12-06 14:20 UTC, rozza commented on driver/src/main/com/mongodb/reactivestreams/client/gridfs/GridFSBuckets.java
> +     * @param database the database instance to use with GridFS
Done

2016-12-06 14:20 UTC, rozza commented on driver/src/main/com/mongodb/reactivestreams/client/MongoDatabase.java
> +
Done

2016-12-06 14:32 UTC, jyemin approved these changes

2016-12-06 14:34 UTC, jyemin commented
If you haven't already, make sure you add an exclude for the internal package when generating javadoc.

2016-12-07 10:34 UTC, closed without merging